### ISSUE TITLE
Remove JDK6 features from 0.2 branch (since it's JDK8)

### ISSUE THREAD

**Issue by ktoso** [lightbend/ssl-config#36] opened 2016-04-07 12:59 UTC

**Comment by dwijnand** [comment] 2018-09-25 16:14
Could someone enumerate the features to remove?

Otherwise I think we should "remove" (close 😉) this ticket.

**Comment by dwijnand** [comment] 2018-09-26 10:07
Duplicate of #87

**Closed by dwijnand** 2018-09-26 10:07 UTC
Labels: 1 - triaged, 2 - pick next, small
